trailingComma = "es5"
tabWidth = 2
useTabs = false
semi = true
singleQuote = false
jsxSingleQuote = false
arrowParens = "always"
printWidth = 80
bracketSpacing = true
htmlWhitespaceSensitivity = "ignore"

[[overrides]]
files = [ "*.html" ]
  [overrides.options]
  printWidth = 360

[[overrides]]
files = [ "*.css", "*.scss" ]
  [overrides.options]
  singleQuote = false
