name: workflow

on:
  push:
  pull_request:

jobs:
  prettier-eslint-checker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Prettier-eslint Checker
        run: yarn checker

  vitest-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Vitest Run
        run: yarn test

  build-scripts:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: React-static Building
        run: yarn build:scripts
        env:
          NODE_ENV: production

  build-storybook:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Storybook-static Building
        run: yarn build-storybook
        env:
          NODE_ENV: production

  deploy-react-static:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: React-static Building
        run: yarn build:scripts
        env:
          NODE_ENV: production

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /react-cognito/

  deploy-storybook-static:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Storybook-static Building
        run: yarn build-storybook
        env:
          NODE_ENV: production

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./storybook-static/
          server-dir: /storybook/
